name: CustomNukes
main: com.gmail.uprial.customnukes.CustomNukes
version: 0.2.12
api-version: '1.14'
commands:
   customnukes:
      description: Reload CustomNukes config
      usage: /customnukes help
      permission:
      permission-message:
permissions:
    customnukes.reload:
        description: Gives access to CustomNukes 'reload' command
        default: op
    customnukes.give:
        description: Gives access to CustomNukes 'give' command
        default: op
    customnukes.explosive.*:
        description: Gives access to craft or use CustomNukes explosives
        default: op
    customnukes.clear:
        description: Gives access to remove all explosive blocks and active repeaters
        default: op